// Mocks generated by Mockito 5.0.17 from annotations
// in unity_test/test/person_bloc_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:unity_test/person.dart' as _i3;
import 'package:unity_test/person_repository.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [PersonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonRepository extends _i1.Mock implements _i2.PersonRepository {
  MockPersonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<dynamic> get listMock => (super
          .noSuchMethod(Invocation.getter(#listMock), returnValue: <dynamic>[])
      as List<dynamic>);
  @override
  List<_i3.Person> getPerson() =>
      (super.noSuchMethod(Invocation.method(#getPerson, []),
          returnValue: <_i3.Person>[]) as List<_i3.Person>);
}
